### ISSUE TITLE
你好，修改web端口启动后request host no logid found"

### ISSUE THREAD

**Issue by a0xpg** [SPuerBRead/Bridge#11]
80端口有其他服务，关闭其他服务在80端口上能正常使用，但是修改server.port=82后，访问web提示request host no logid found，想请教下修改配置文件后是否还需要在代码中进行其他修改。

**Comment by a0xpg** [comment]
启动的时候，加上了端口   java -jar  bridge.jar dns.xx.com  dnslog.xx.com:82 xx.xx.xx.xx  xxxx，运行没问题，但是使用会出现异常，有没有办法在不关闭apache服务下运行在80端口

**Comment by SPuerBRead** [comment]
> 启动的时候，加上了端口 java -jar bridge.jar dns.xx.com dnslog.xx.com:82 xx.xx.xx.xx xxxx，运行没问题，但是使用会出现异常，有没有办法在不关闭apache服务下运行在80端口

换个机器走nginx出去
