### ISSUE TITLE
无法注册，无法登录

### ISSUE THREAD

**Issue by langyajiekou** [SPuerBRead/Bridge#12]
无法注册，无法登录

**Comment by SPuerBRead** [comment]
确定是否按照步骤安装，附加详细的说明，”无法注册，无法登录“不能确定哪里有问题

**Comment by SPuerBRead** [comment]
> 无法注册，无法登录
确定是否按照步骤安装，附加详细的说明，”无法注册，无法登录“不能确定哪里有问题

**Comment by langyajiekou** [comment]
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS                                    NAMES
f2e7308b301c   bridge-master_bridge   "nohup java -jar /br…"   59 minutes ago   Up 59 minutes   0.0.0.0:53->53/udp, 0.0.0.0:80->80/tcp   bridge-master_bridge_1
4e24c3989794   mysql:5.7              "docker-entrypoint.s…"   59 minutes ago   Up 59 minutes   3306/tcp, 33060/tcp                      mysql

感觉这个mysql是不是没有挂上去？怎么来了个33060端口？

**Comment by langyajiekou** [comment]
> > 无法注册，无法登录
> > 确定是否按照步骤安装，附加详细的说明，”无法注册，无法登录“不能确定哪里有问题

按步骤启动docker后，在登录页面先行注册，不管怎么输入，都会提示该账号已经存在。直接访问mysql数据库中的表，根本就没有数据插入。所以怀疑根本就没有根数据库进行连接，哪里可以追踪到日志？

**Comment by SPuerBRead** [comment]
> > > 无法注册，无法登录
> > > 确定是否按照步骤安装，附加详细的说明，”无法注册，无法登录“不能确定哪里有问题
> 
> 按步骤启动docker后，在登录页面先行注册，不管怎么输入，都会提示该账号已经存在。直接访问mysql数据库中的表，根本就没有数据插入。所以怀疑根本就没有根数据库进行连接，哪里可以追踪到日志？

看起来现在mysql 5.7的镜像更新之后连接mysql有点问题，我周末看下吧

**Comment by langyajiekou** [comment]
> > > > 无法注册，无法登录
> > > > 确定是否按照步骤安装，附加详细的说明，”无法注册，无法登录“不能确定哪里有问题
> > 
> > 
> > 按步骤启动docker后，在登录页面先行注册，不管怎么输入，都会提示该账号已经存在。直接访问mysql数据库中的表，根本就没有数据插入。所以怀疑根本就没有根数据库进行连接，哪里可以追踪到日志？
> 
> 看起来现在mysql 5.7的镜像更新之后连接mysql有点问题，我周末看下吧

解决了嘛？

**Comment by SPuerBRead** [comment]
> > > > > 无法注册，无法登录
> > > > > 确定是否按照步骤安装，附加详细的说明，”无法注册，无法登录“不能确定哪里有问题
> > > 
> > > 
> > > 按步骤启动docker后，在登录页面先行注册，不管怎么输入，都会提示该账号已经存在。直接访问mysql数据库中的表，根本就没有数据插入。所以怀疑根本就没有根数据库进行连接，哪里可以追踪到日志？
> > 
> > 
> > 看起来现在mysql 5.7的镜像更新之后连接mysql有点问题，我周末看下吧
> 
> 解决了嘛？

得等下，上周没抽出时间弄，这周末看下

**Comment by SPuerBRead** [comment]
> > > > > 无法注册，无法登录
> > > > > 确定是否按照步骤安装，附加详细的说明，”无法注册，无法登录“不能确定哪里有问题
> > > 
> > > 
> > > 按步骤启动docker后，在登录页面先行注册，不管怎么输入，都会提示该账号已经存在。直接访问mysql数据库中的表，根本就没有数据插入。所以怀疑根本就没有根数据库进行连接，哪里可以追踪到日志？
> > 
> > 
> > 看起来现在mysql 5.7的镜像更新之后连接mysql有点问题，我周末看下吧
> 
> 解决了嘛？

已修复
