### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by chen1sheng** [SPuerBRead/Bridge#16]
jdk8编译报错如下：

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project bridge: Compilation failure
[ERROR] /Users/chen/Downloads/Bridge-master/src/main/java/bridge/intercept/WebLogIntercept.java:[38,72] 找不到符号
[ERROR]   符号:   方法 strip()
[ERROR]   位置: 类 java.lang.String
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

用idea打开看说是strip是jdk11的特性。。手动改成trim了🤣🤣🤣

**Comment by SPuerBRead** [comment]
> jdk8编译报错如下：
> 
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project bridge: Compilation failure [ERROR] /Users/chen/Downloads/Bridge-master/src/main/java/bridge/intercept/WebLogIntercept.java:[38,72] 找不到符号 [ERROR] 符号: 方法 strip() [ERROR] 位置: 类 java.lang.String [ERROR] [ERROR] -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> 
> 用idea打开看说是strip是jdk11的特性。。手动改成trim了🤣🤣🤣

https://github.com/SPuerBRead/Bridge/pull/15/files 修改一下，可能他那边版本JDK比较高，没细看修改的代码就merge了，稍等我修改下

**Comment by SPuerBRead** [comment]
> jdk8编译报错如下：
> 
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project bridge: Compilation failure [ERROR] /Users/chen/Downloads/Bridge-master/src/main/java/bridge/intercept/WebLogIntercept.java:[38,72] 找不到符号 [ERROR] 符号: 方法 strip() [ERROR] 位置: 类 java.lang.String [ERROR] [ERROR] -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> 
> 用idea打开看说是strip是jdk11的特性。。手动改成trim了🤣🤣🤣

https://github.com/SPuerBRead/Bridge/pull/15/files 提交的代码，可能他那边版本JDK比较高，没细看修改的代码就merge了，稍等我修改下
