### ISSUE TITLE
docker中启动命令中的服务器地址是设置服务器真实地址还是容器的地址？

### ISSUE THREAD

**Issue by 0x5826** [SPuerBRead/Bridge#2]
docker中部署的这个地址是写服务器真实地址还是可以保持默认？

**Comment by SPuerBRead** [comment]
`command: nohup java -jar /bridge/target/bridge-1.0-SNAPSHOT.jar dns.dnslog.com dnslog.dnslog.com 10.10.10.10 a1b2c3d4 &`
这里的10.10.10.10么，需要真实地址，地址相关的都根据实际情况配置

**Comment by 0x5826** [comment]
OK啦，我直接填我服务器的公网地址，目前运行没有问题。
这个系统太屌了，给个大大的赞！
