### ISSUE TITLE
你好，第一次搭建完毕后提示message	"request host no logid found"

### ISSUE THREAD

**Issue by lxl315** [SPuerBRead/Bridge#3]
域名已经按要求解析好了

**Comment by SPuerBRead** [comment]
每个用户都有一个的logid，如果logid是1，ping的时候需要访问xxxx.1.xxx.com，api信息页有详细说明

**Comment by lxl315** [comment]
谢谢这个搞好了，但是还有一个新问题。配置了ns解析，然后我ping 1.dns.xxx.com  不通，web控制台也看不到记录，是怎么会是？服务器不需要做别的设置么？比如开启53端口这些？

**Comment by SPuerBRead** [comment]
确认域名和服务配置的都没有问题，如果还不通，看下服务器，不能用腾讯云的服务器，阿里云没有测试过，国内的应该都不行

**Comment by lxl315** [comment]
![image](https://user-images.githubusercontent.com/15553644/69861636-b9a1a780-12d3-11ea-9174-74bd79ba8da6.png)
你好主机是香港阿里云，域名是在腾讯购买的。解析如上图，是因为域名解析的原因么

**Comment by swrite** [comment]
我也遇到了，{"message":"request host no logid found","status":"error"}

**Comment by swrite** [comment]
搭建完平台后，访问web 界面 ，出现{"message":"request host no logid found","status":"error"}
